import * as fs from 'fs';
import * as path from 'path';
import { TradeSignal } from './fractalAnalyzer';
import { logger } from './logger';

export interface TradeRecord {
  id: string;
  symbol: string;
  type: 'LONG' | 'SHORT';
  phase: string;
  entryZone: [number, number];
  fillPrice?: number;       // v1.3: real fill price from Capital.com
  stopLoss: number;
  target1: number;
  target2: number;
  riskReward: number;
  openedAt: string;       // ISO
  closedAt?: string;      // ISO — filled when closed
  closePrice?: number;
  pnlPips?: number;
  pnlEUR?: number;
  result?: 'WIN' | 'LOSS' | 'BREAKEVEN';
  dealId?: string;
}

const LOG_DIR  = path.join(process.cwd(), 'data');
const LOG_FILE = path.join(LOG_DIR, 'trades.json');

function ensureDir(): void {
  if (!fs.existsSync(LOG_DIR)) fs.mkdirSync(LOG_DIR, { recursive: true });
}

export function loadTrades(): TradeRecord[] {
  ensureDir();
  if (!fs.existsSync(LOG_FILE)) return [];
  try {
    return JSON.parse(fs.readFileSync(LOG_FILE, 'utf-8')) as TradeRecord[];
  } catch {
    return [];
  }
}

function saveTrades(trades: TradeRecord[]): void {
  ensureDir();
  fs.writeFileSync(LOG_FILE, JSON.stringify(trades, null, 2), 'utf-8');
}

export function logOpenTrade(signal: TradeSignal, dealId: string): TradeRecord {
  const trades = loadTrades();
  const record: TradeRecord = {
    id: dealId,
    symbol: signal.symbol,
    type: signal.type,
    phase: signal.phase,
    entryZone: signal.entryZone,
    fillPrice: signal.currentPrice, // v1.3: real fill price from Capital.com
    stopLoss: signal.stopLoss,
    target1: signal.target1,
    target2: signal.target2,
    riskReward: signal.riskReward,
    openedAt: new Date().toISOString(),
    dealId,
  };
  trades.push(record);
  saveTrades(trades);
  logger.info(`Trade logged: ${record.symbol} ${record.type} [${dealId}]`);
  return record;
}

export function logClosedTrade(
  dealId: string,
  closePrice: number,
  closedAt: string
): TradeRecord | null {
  const trades = loadTrades();
  const idx = trades.findIndex(t => t.id === dealId);
  if (idx === -1) return null;

  const trade = trades[idx];
  const pip = trade.symbol.includes('JPY') ? 0.01 : 0.0001;
  // v1.3: Use fill price if available, otherwise fall back to entry zone midpoint
  const entryRef = trade.fillPrice ?? (trade.entryZone[0] + trade.entryZone[1]) / 2;
  const pnlPips = trade.type === 'LONG'
    ? (closePrice - entryRef) / pip
    : (entryRef - closePrice) / pip;

  const pipValueEUR = 8.5;
  const stopPips = Math.abs(entryRef - trade.stopLoss) / pip;
  const lotSize = Math.min(Math.max(Math.round(100 / (stopPips * pipValueEUR) * 100) / 100, 0.01), 10);
  const pnlEUR = pnlPips * pipValueEUR * lotSize;

  trade.closedAt   = closedAt;
  trade.closePrice = closePrice;
  trade.pnlPips    = Math.round(pnlPips * 10) / 10;
  trade.pnlEUR     = Math.round(pnlEUR * 100) / 100;
  trade.result     = pnlPips > 0.5 ? 'WIN' : pnlPips < -0.5 ? 'LOSS' : 'BREAKEVEN';

  trades[idx] = trade;
  saveTrades(trades);
  logger.info(`Trade closed: ${trade.symbol} ${trade.result} | ${trade.pnlPips} pips | €${trade.pnlEUR}`);
  return trade;
}

// Generate TradingView Pine Script with trade markers
export function generatePineScript(): string {
  const trades = loadTrades().filter(t => t.closedAt);
  if (trades.length === 0) return '// No closed trades yet';

  const lines: string[] = [
    '//@version=5',
    'indicator("TTFM Trade Log", overlay=true)',
    '',
    '// Auto-generated by TTrades Bot',
    `// Generated: ${new Date().toUTCString()}`,
    `// Total trades: ${trades.length}`,
    '',
  ];

  trades.forEach((t, i) => {
    const openTs  = Math.floor(new Date(t.openedAt).getTime() / 1000);
    const closeTs = Math.floor(new Date(t.closedAt!).getTime() / 1000);
    const entryMid = (t.entryZone[0] + t.entryZone[1]) / 2;
    const color = t.result === 'WIN' ? 'color.green' : t.result === 'LOSS' ? 'color.red' : 'color.gray';
    const arrow = t.type === 'LONG' ? 'label.style_arrow_up' : 'label.style_arrow_down';
    const dec = t.symbol.includes('JPY') ? 3 : 5;

    lines.push(`// Trade ${i + 1}: ${t.symbol} ${t.type} | ${t.result} | ${t.pnlPips} pips`);
    lines.push(`var label lbl_${i} = na`);
    lines.push(`if bar_index == 0`);
    lines.push(`    lbl_${i} := label.new(`);
    lines.push(`        x = ${openTs},`);
    lines.push(`        y = ${entryMid.toFixed(dec)},`);
    lines.push(`        text = "${t.symbol}\\n${t.type}\\n${t.pnlPips}p",`);
    lines.push(`        style = ${arrow},`);
    lines.push(`        color = ${color},`);
    lines.push(`        textcolor = color.white,`);
    lines.push(`        xloc = xloc.bar_time`);
    lines.push(`    )`);
    lines.push('');
  });

  return lines.join('\n');
}

export function savePineScript(): string {
  ensureDir();
  const script = generatePineScript();
  const filePath = path.join(LOG_DIR, 'ttfm_trades.pine');
  fs.writeFileSync(filePath, script, 'utf-8');
  logger.info(`Pine Script saved to ${filePath}`);
  return filePath;
}
